# Generated by Django 2.1.7 on 2019-03-03 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Photo'),
        ),
    ]
