# Generated by Django 2.1.7 on 2019-03-03 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190303_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='photolike',
            name='liked_by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
