# Generated by Django 2.1.7 on 2019-03-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_photolike_liked_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photolike',
            old_name='liked_by_user',
            new_name='user',
        ),
    ]
