# Generated by Django 2.1.7 on 2019-03-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190303_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.ImageField(upload_to='../media'),
        ),
    ]
